command: ['npm', 'run', 'start']
env:
  - name: DATABRICKS_SERVING_ENDPOINT_NAME
    valueFrom: serving-endpoint
  - name: MODEL_GPT_OSS_ENDPOINT_NAME
    valueFrom: serving-endpoint
  - name: MODEL_LLAMA_ENDPOINT_NAME
    valueFrom: serving-endpoint-llama
  - name: MODEL_QWEN_ENDPOINT_NAME
    valueFrom: serving-endpoint-qwen
  - name: MODEL_EMBED_ENDPOINT_NAME
    valueFrom: serving-endpoint-embed
  - name: LAKEBASE_ENDPOINT
    valueFrom: postgres